import Mathdemo.CRealPresented
import Mathdemo.BishopSec1Presented
import Mathdemo.BishopSec3Presented
import Mathdemo.BishopSec3PresentedEnhancementsC
import Mathdemo.BishopChengTheorem415Prop
import Mathdemo.BishopChengTheorem415FullSetData
import Mathdemo.CheckSec3PortAxioms
import Mathdemo.CheckDCTV2Axioms
import Mathdemo.CheckBishopChengTheorem415PropAxioms

import Mathdemo.ChoiceFreeDCTExamples
import Mathdemo.ChoiceFreeDCTConcreteExamples

-- Mathematical reading of the development, and the source definition it renders.
import Mathdemo.MathematicalInterface
import Mathdemo.SourceIntegrationSpaceDef11
import Mathdemo.DiracIntegrationSpace

import ChoiceFreeMeasureDCTPublic
