import ChoiceFreeMeasureDCTPublic
import Mathdemo.ChoiceFreeDCTExamples
import Mathdemo.ChoiceFreeDCTConcreteExamples
import Mathdemo.CheckSec3PortAxioms

/-!
# Supplementary audit module

This file checks the public aliases and implementation declarations used by
the paper, and prints their dependency profiles.
-/

#check ChoiceFreeMeasureDCT.profile_partition_dataC
#check ChoiceFreeMeasureDCT.profile_level_sets_integrable_apartC
#check ChoiceFreeMeasureDCT.profile_level_sets_integrable_apart_globalC
#check ChoiceFreeMeasureDCT.uniform_complement_from_profile_levelsC
#check ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergenceC
#check ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergenceC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profileC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profileC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profileC
#check ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergence_autoC
#check ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergence_autoC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profile_autoC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profile_autoC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profile_autoC
#check ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_on_full_dataC
#check ChoiceFreeMeasureDCT.integral_convergence_from_majorant_on_full_dataC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_dataC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_data_autoC
#check ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_good_set_data_autoC
#check ChoiceFreeMeasureDCT.bishop_cheng_dominated_convergence_propC

#check BishopSec3P.lemma_3_4DataC
#check BishopSec3P.thm_3_6_forall_apart_measureC
#check BishopSec3P.lemma43UniformComplementData_of_majorantC
#check BishopSec3P.thm_4_15_integral_convergence_from_majorant_smooth_measure_convergeC
#check BishopSec3P.goalB_dominated_convergence_dataC
#check BishopSec3P.goalB_classical_dominated_convergence_dataC
#check BishopSec1P.RepLeOnFullDataC
#check BishopSec1P.RepAbsLeOnFullDataC
#check BishopSec1P.DominatedOnFullDataC
#check BishopSec1P.DominatedOnFullDataC.ofGlobal
#check BishopSec3P.lemma43UniformComplementData_of_majorantOnFullDataC
#check BishopSec3P.absError_le_absMajorant_add_absLimit_onFullDataC
#check BishopSec3P.dominatedConvergence_from_pointwiseMajorantOnFullData_autoC
#check BishopSec3P.bishop_cheng_l1_error_tends_zero_propC_with_majorant
#check BishopSec3P.bishop_cheng_thm_4_15_propC
#check BishopSec3P.thm36B_smoothPointDataC_construct
#check BishopSec3P.lemma43DyadicSmoothDataC_construct

#print axioms ChoiceFreeMeasureDCT.profile_partition_dataC
#print axioms ChoiceFreeMeasureDCT.profile_level_sets_integrable_apartC
#print axioms ChoiceFreeMeasureDCT.profile_level_sets_integrable_apart_globalC
#print axioms ChoiceFreeMeasureDCT.uniform_complement_from_profile_levelsC
#print axioms ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergenceC
#print axioms ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergenceC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profileC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profileC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profileC
#print axioms ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergence_autoC
#print axioms ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergence_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profile_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profile_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profile_autoC
#print axioms ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_on_full_dataC
#print axioms ChoiceFreeMeasureDCT.integral_convergence_from_majorant_on_full_dataC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_dataC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_data_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_good_set_data_autoC
#print axioms ChoiceFreeMeasureDCT.bishop_cheng_dominated_convergence_propC

#print axioms BishopSec3P.lemma_3_4DataC
#print axioms BishopSec3P.thm_3_6_forall_apart_measureC
#print axioms BishopSec3P.lemma43UniformComplementData_of_majorantC
#print axioms BishopSec3P.thm_4_15_integral_convergence_from_majorant_smooth_measure_convergeC
#print axioms BishopSec3P.goalB_dominated_convergence_dataC
#print axioms BishopSec3P.goalB_classical_dominated_convergence_dataC
#print axioms BishopSec1P.RepLeOnFullDataC
#print axioms BishopSec1P.RepAbsLeOnFullDataC
#print axioms BishopSec1P.DominatedOnFullDataC
#print axioms BishopSec1P.DominatedOnFullDataC.ofGlobal
#print axioms BishopSec3P.lemma43UniformComplementData_of_majorantOnFullDataC
#print axioms BishopSec3P.absError_le_absMajorant_add_absLimit_onFullDataC
#print axioms BishopSec3P.dominatedConvergence_from_pointwiseMajorantOnFullData_autoC
#print axioms BishopSec3P.bishop_cheng_l1_error_tends_zero_propC_with_majorant
#print axioms BishopSec3P.bishop_cheng_thm_4_15_propC
#print axioms BishopSec3P.thm36B_smoothPointDataC_construct
#print axioms BishopSec3P.lemma43DyadicSmoothDataC_construct

-- CReal countable-avoidance support added in the v0.2 development line.
#check BishopSec3P.thm36B1_interval_stepC
#check BishopSec3P.thm36B1_intervalSeq_nestedC
#check BishopSec3P.thm36B1_leftSeq_monoC
#check BishopSec3P.thm36B1_rightSeq_antitoneC
#check BishopSec3P.thm36B1_leftSeqCauchyDataC
#check BishopSec3P.thm36B1_leftLimitReprC
#check BishopSec3P.thm36B1_limit_apartC
#check BishopSec3P.thm36B1_apartPointDataC
#check BishopSec3P.thm36B_smoothPointDataC_construct
#check BishopSec3P.lemma43DyadicSmoothDataC_construct

-- Abstract application examples.
#check ChoiceFreeMeasureDCT.abstract_good_set_dct_applicationC
#check ChoiceFreeMeasureDCT.abstract_l1_error_endpoint_applicationC
#check ChoiceFreeMeasureDCT.abstract_good_set_dct_application_autoC
#check ChoiceFreeMeasureDCT.abstract_l1_error_endpoint_application_autoC
#check ChoiceFreeMeasureDCT.abstract_bishop_cheng_prop_applicationC

-- Nonempty concrete zero-integral example.
#check ChoiceFreeMeasureDCT.punit_zero_dct_application_autoC

-- CReal interval sandwich and width-control support.
#check BishopSec3P.thm36B1_leftSeq_le_rightSeqC
#check BishopSec3P.thm36B1_leftSeq_absSub_le_widthC
#check BishopSec3P.thm36B1_leftSeq_absSub_le_widthScaleC

#print axioms ChoiceFreeMeasureDCT.punit_zero_dct_application_autoC
