#!/usr/bin/env python3
"""Emit a Lean file that `#check`s every frozen name of kind `decl`.

The paper cites these identifiers by name.  Asking Lean to elaborate each name
is stronger than searching the sources for the last component of the name,
which an unrelated declaration elsewhere in the tree can satisfy.

Names are elaborated with the development's own namespaces opened, so that a
name may be listed in the form the paper prints it.  The opened namespaces are
fixed here and are part of what the check means.
"""
import argparse, io, re, sys

OPENS = ["BishopCheng", "BishopCReal", "BishopSec1P", "BishopSec3P", "BishopC",
         "ChoiceFreeMeasureDCT"]
IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_.'!?]*$")


def load(path):
    """Return {kind: [name, ...]} from a typed frozen-name list."""
    kinds = {}
    for lineno, line in enumerate(io.open(path, encoding="utf-8"), 1):
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        parts = s.split(None, 1)
        if len(parts) != 2:
            raise SystemExit(f"{path}:{lineno}: expected '<kind> <name>', got {s!r}")
        kinds.setdefault(parts[0], []).append(parts[1].strip())
    return kinds


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--names", default="tools/frozen_names.txt")
    ap.add_argument("--imports", default="Mathdemo,ChoiceFreeMeasureDCTPublic")
    ap.add_argument("--output", required=True)
    a = ap.parse_args()
    kinds = load(a.names)
    decls = kinds.get("decl", [])
    bad = [n for n in decls if not IDENT.match(n)]
    if bad:
        print("not identifier-shaped: " + ", ".join(bad), file=sys.stderr)
        return 1
    out = [f"import {m}" for m in a.imports.split(",")]
    out += ["", "-- generated by tools/generate_frozen_names_check.py; do not edit",
            "set_option linter.all false", "", "open " + " ".join(OPENS), ""]
    out += [f"#check @{n}" for n in decls]
    io.open(a.output, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"frozen_decl_names={len(decls)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
