/-
  public_surface_check.lean --- the invariant that a refactor must preserve.

      lake env lean tools/public_surface_check.lean > logs/public_surface.txt 2>&1

  Prints the elaborated type and the kernel axiom footprint of every public
  alias.  A refactor of the development must leave this output byte-identical.
-/
import ChoiceFreeMeasureDCTPublic

#check @ChoiceFreeMeasureDCT.profile_partition_dataC
#check @ChoiceFreeMeasureDCT.profile_smooth_away_from_sequenceC
#check @ChoiceFreeMeasureDCT.profile_level_sets_integrable_apartC
#check @ChoiceFreeMeasureDCT.profile_level_sets_integrable_apart_globalC
#check @ChoiceFreeMeasureDCT.uniform_complement_from_profile_levelsC
#check @ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergenceC
#check @ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergenceC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profileC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profileC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profileC
#check @ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergence_autoC
#check @ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergence_autoC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profile_autoC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profile_autoC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profile_autoC
#check @ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_on_full_dataC
#check @ChoiceFreeMeasureDCT.integral_convergence_from_majorant_on_full_dataC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_dataC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_data_autoC
#check @ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_good_set_data_autoC
#check @ChoiceFreeMeasureDCT.bishop_cheng_dominated_convergence_propC
#print axioms ChoiceFreeMeasureDCT.profile_partition_dataC
#print axioms ChoiceFreeMeasureDCT.profile_smooth_away_from_sequenceC
#print axioms ChoiceFreeMeasureDCT.profile_level_sets_integrable_apartC
#print axioms ChoiceFreeMeasureDCT.profile_level_sets_integrable_apart_globalC
#print axioms ChoiceFreeMeasureDCT.uniform_complement_from_profile_levelsC
#print axioms ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergenceC
#print axioms ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergenceC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profileC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profileC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profileC
#print axioms ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_measure_convergence_autoC
#print axioms ChoiceFreeMeasureDCT.integral_convergence_from_majorant_measure_convergence_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_error_majorant_profile_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_profile_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_good_set_profile_autoC
#print axioms ChoiceFreeMeasureDCT.l1_error_convergence_from_majorant_on_full_dataC
#print axioms ChoiceFreeMeasureDCT.integral_convergence_from_majorant_on_full_dataC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_dataC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_data_autoC
#print axioms ChoiceFreeMeasureDCT.dominated_convergence_from_pointwise_majorant_on_full_good_set_data_autoC
#print axioms ChoiceFreeMeasureDCT.bishop_cheng_dominated_convergence_propC
